version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 545009852032.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t my-flask-app .
      - docker tag my-flask-app:latest 545009852032.dkr.ecr.us-east-1.amazonaws.com/my-flask-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 545009852032.dkr.ecr.us-east-1.amazonaws.com/my-flask-app:latest